### ISSUE TITLE
[Suggestion] Ped Whitelist

### ISSUE THREAD

**Issue by dropfile14** [inferno-collection/Police-Panic#1]
**Is your feature request related to a problem? Please describe.**

No problem, Adding a whitelist to peds entity 

**Describe the solution you would like**

**Describe alternatives you have considered**

**Additional context**

**Comment by ScottUK** [comment]
Just to clear up, you want to add a whitelist to certain peds?

**Comment by cm8263** [comment]
No clarification provided.
