### ISSUE TITLE
1st time it works. On 2nd it doesent play sound

### ISSUE THREAD

**Issue by gASSSU** [inferno-collection/Police-Panic#3]
1st time when i use /panic everything works. After that i did it 2nd time and sound didn't work at all. Only error in console: Cannot read property 'replace' of undefined (@chat/html/vendor/vue.2.3.3.min.js:6)

**Comment by cm8263** [comment]
Are you using any custom chat resources? The error is not from the Panic script itself.

**Comment by gASSSU** [comment]
No. I have normal chat with just background color changed.

**Comment by cm8263** [comment]
Identified the issue; is affecting multiple IC resources.

**Comment by cm8263** [comment]
Must have been drunk when I added that last message... anyway, issue resolved in https://github.com/inferno-collection/Police-Panic/releases/tag/v1.22-beta.
